#!/usr/bin/env zsh
# Copyright © 2017 Paul Viallard <paul.viallard@gmail.com>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.

ENVIRONMENT=$HOME/.shell
VIM_ENVIRONMENT=$HOME/.vim
NEOVIM_ENVIRONMENT=$HOME/.config/nvim

# We install the shell
rm -rf $HOME/.zshrc
echo "source ~/.shell/shell_profile.zsh" > $HOME/.zshrc

# We install the plugins for zsh
cd $ENVIRONMENT/prompt/
git clone git://github.com/zsh-users/zsh-autosuggestions autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git highlighting

# We install different configurations
rm -rf $HOME/.tmux.conf
ln $ENVIRONMENT/config/tmux.conf $HOME/.tmux.conf

# We install vim
rm -rf $HOME/.vimrc
rm -rf $VIM_ENVIRONMENT
mkdir -p $VIM_ENVIRONMENT/colors
ln $ENVIRONMENT/config/vim_profile.vim $HOME/.vimrc
ln $ENVIRONMENT/config/vim_color.vim $VIM_ENVIRONMENT/colors/paulviallard.vim

# We install the plugins for vim
mkdir -p $VIM_ENVIRONMENT/autoload $VIM_ENVIRONMENT/bundle && \
curl -LSso $VIM_ENVIRONMENT/autoload/pathogen.vim https://tpo.pe/pathogen.vim
git clone git://github.com/tpope/vim-fugitive.git $VIM_ENVIRONMENT/bundle/vim-fugitive
git clone https://github.com/scrooloose/nerdtree.git $VIM_ENVIRONMENT/bundle/nerdtree
git clone https://github.com/scrooloose/nerdcommenter.git $VIM_ENVIRONMENT/bundle/nerdcommenter
git clone https://github.com/vim-latex/vim-latex.git  $VIM_ENVIRONMENT/bundle/vim-latex
git clone https://github.com/jalvesaq/Nvim-R.git $VIM_ENVIRONMENT/bundle/Nvim-R
git clone --recursive https://github.com/davidhalter/jedi-vim.git $VIM_ENVIRONMENT/bundle/jedi-vim
git clone --recursive https://github.com/python-mode/python-mode $VIM_ENVIRONMENT/bundle/python-mode


git clone https://github.com/ervandew/supertab.git $VIM_ENVIRONMENT/bundle/supertab

# We install neovim
mkdir -p $NEOVIM_ENVIRONMENT
ln $ENVIRONMENT/config/vim_profile.vim $NEOVIM_ENVIRONMENT/init.vim
ln -s $VIM_ENVIRONMENT/colors $NEOVIM_ENVIRONMENT/colors
ln -s $VIM_ENVIRONMENT/autoload $NEOVIM_ENVIRONMENT/autoload
ln -s $VIM_ENVIRONMENT/bundle $NEOVIM_ENVIRONMENT/bundle

# We create a local branch
cd $ENVIRONMENT; git checkout -b local
source $HOME/.zshrc
