#!/usr/bin/env python3
# Copyright © 2019 Paul Viallard <paul.viallard@gmail.com>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.

from subprocess import check_output, DEVNULL

# We set the color for the printing
COLOR_DEFAULT_STRING = "#[fg=white]"
COLOR_WHOAMI_STRING = "#[fg=colour12 bold]"
COLOR_HOSTNAME_STRING = "#[fg=colour12 bold]"
COLOR_AT_STRING = "#[fg=white bold]"

# We get the username
whoami_string = check_output(
    "whoami; exit 0", shell=True, stderr=DEVNULL)
whoami_string = whoami_string.decode("utf-8")
whoami_string = whoami_string.replace("\n", "")

# We get the hostname
hostname_string = check_output(
    "hostname -s; exit 0", shell=True, stderr=DEVNULL)
hostname_string = hostname_string.decode("utf-8")
hostname_string = hostname_string.replace("\n", "")

# We print the status
status_string = COLOR_WHOAMI_STRING+whoami_string
status_string += COLOR_AT_STRING+"@"
status_string += COLOR_HOSTNAME_STRING+hostname_string
status_string += COLOR_DEFAULT_STRING
print(status_string)
