#!/usr/bin/env python3
# Copyright © 2019 Paul Viallard <paul.viallard@gmail.com>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.

from os import environ
from argparse import ArgumentParser

# We set the color for the printing
COLOR_DEFAULT_STRING = "#[fg=white]"
COLOR_FILE_STRING = "#[fg=colour12 bold]"
COLOR_PATH_STRING = "#[fg=white bold]"

# We get the home of the user
HOME_STRING = environ["HOME"]

# We create the parser
arg_parser = ArgumentParser(
    description="print (for tmux) the path of the working directory"
)
arg_parser.add_argument(
    "pwd", metavar="pwd", type=str,
    help="current working directory"
)
arg_list = arg_parser.parse_args()

# We get the path of the directory
# (We assume that the path is correct)
pwd_string = arg_list.pwd

# We add the colors to the path of the working directory
pwd_string = pwd_string.replace(HOME_STRING, "~")
pwd_list = pwd_string.split("/")
pwd_list = [COLOR_FILE_STRING+pwd_file for pwd_file in pwd_list]
pwd_string = (COLOR_PATH_STRING+"/").join(pwd_list)
pwd_string += COLOR_DEFAULT_STRING

# We print the path
print(pwd_string, end="")
