#!/usr/bin/env python3
# Copyright © 2019 Paul Viallard <paul.viallard@gmail.com>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.

from subprocess import check_output, DEVNULL
from argparse import ArgumentParser

# We set the color for the printing
COLOR_DEFAULT_STRING = "#[fg=white bg=black]"
COLOR_SEPARATOR_STRING = "#[fg=black bg=white bold]"

# We set the separator
SEPARATOR = "|"

# We set the path of the scripts to execute and print
SCRIPT_STATUS_LIST = [
    "~/.dotfiles/tmux/print-directory",
    "~/.dotfiles/tmux/print-status-git"
]

#  We create the parser
arg_parser = ArgumentParser(
    description="print (for tmux) the right status"
)
arg_parser.add_argument(
    "pwd", metavar="pwd", type=str,
    help="current working directory"
)
arg_list = arg_parser.parse_args()

#  We get the path of the directory
pwd = arg_list.pwd

# For each status script,
status_string = ""
for i in range(len(SCRIPT_STATUS_LIST)):
    # We get the output
    script_status_string = check_output(
        SCRIPT_STATUS_LIST[i]+" \""+str(pwd)
        + "\"; exit 0", shell=True, stderr=DEVNULL)
    script_status_string = script_status_string.decode("utf-8")
    script_status_string = script_status_string.replace("\n", "")

    # We separate the output with the separator
    if(i > 0 and len(script_status_string) != 0):
        status_string += " "+COLOR_SEPARATOR_STRING+SEPARATOR
        status_string += COLOR_DEFAULT_STRING+" "

    # We add the script output to the status
    status_string += script_status_string

# We print the status
print(status_string)
